server {
    listen 8080;  # Nasłuchuj na porcie 8080 wewnątrz kontenera
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
